version: '3'

services:
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: todo
      MYSQL_USER: dev
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: web
    depends_on:
      - database
    volumes:
      - ./:/app/
    ports:
      - "80:80"
    links:
      - php
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php
    volumes:
      - .:/app/
